<?xml version="1.0" encoding="UTF-8"?>
<project name="CajeroATM" default="run" basedir=".">

    <property name="src.dir"   value="src"/>
    <property name="build.dir" value="build"/>
    <property name="dist.dir"  value="dist"/>
    <property name="main.class" value="cajeroatm.CajeroATM"/>

    <target name="clean">
        <delete dir="${build.dir}"/>
        <delete dir="${dist.dir}"/>
    </target>

    <target name="compile">
        <mkdir dir="${build.dir}/classes"/>
        <javac srcdir="${src.dir}" destdir="${build.dir}/classes" includeantruntime="false"/>
    </target>

    <target name="run" depends="compile">
        <java classname="${main.class}" classpath="${build.dir}/classes" fork="true"/>
    </target>

    <target name="jar" depends="compile">
        <mkdir dir="${dist.dir}"/>
        <jar destfile="${dist.dir}/CajeroATM.jar" basedir="${build.dir}/classes">
            <manifest>
                <attribute name="Main-Class" value="${main.class}"/>
            </manifest>
        </jar>
    </target>

</project>
